name: Create Release

on:
  push:
    tags:
      - '*'

jobs:
  create_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Read release notes
        id: release_notes
        run: |
          TITLE=$(sed -n 's/^# //p' release_notes.md)
          BODY=$(sed '1d' release_notes.md)
          echo "title<<EOF" >> $GITHUB_OUTPUT
          echo "$TITLE" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          echo "body<<EOF" >> $GITHUB_OUTPUT
          echo "$BODY" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ steps.release_notes.outputs.title }}
          body: ${{ steps.release_notes.outputs.body }}
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
